services:
  api:
    build: .
    ports:
      - 8000:8000
    networks:
      - elastic
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - ollama
      - elasticsearch
    volumes:
      - .:/src

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ~/.ollama:/root/.ollama
    networks:
      - elastic

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
